[app]
name = "Mobile Messaging App"
version = "0.1.0"
description = "A mobile messaging app that can be exported/compiled to android and IOS. The app allows logging in with signal, discord, IRC, matrix, and handles SMS on android."

[build]
distDir = "../dist"
devPath = "http://localhost:5000"

[tauri]
embeddedServer = { active = true }
bundle = { active = true }
allowlist = { all = true }

[window]
title = "Mobile Messaging App"
width = 800
height = 600

[styles]
main = "src/styles/main.css"
login = "src/styles/login.css"
messaging = "src/styles/messaging.css"
compile = "src/styles/compile.css"
picocss = "src/styles/picocss.css"

[assets]
logo = "src/assets/logo.png"
favicon = "src/assets/favicon.ico"

[dependencies]
tauri = "0.14.1"
picocss = "0.1.0"